### PR TITLE
Responsiveness and New Buttons

### PR DESCRIPTION
**Pull request by thw26**
Columns may be best moved to another component or the pop up menu.

### CODE REVIEW

**Comment by thw26** [comment]
This needs to be delayed; the mobile editor now has too many buttons. I'm going to move buttons into the pop up menu.

**Comment by thw26** [comment]
I have implemented basic responsiveness and I have run several tests leading to additional modifications. This should be good to be pulled in now, unless, of course, I have missed something.

**Comment by iunctis** [comment]
I'll test when I can and push the commits if it's ok

**Comment by thw26** [comment]
Sounds great. Let me know if I can help with anything.

**Pull request merged**
